services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: t3 # Password root untuk MySQL
      MYSQL_DATABASE: ecourbancity # Nama database yang digunakan
      MYSQL_USER: user # Nama user MySQL
      MYSQL_PASSWORD: t3 # Password untuk user MySQL
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    volumes:
      - "./database/sql:/docker-entrypoint-initdb.d"

  web:
    build: ./web-app/
    ports:
      - "80:80" # Port aplikasi tetap pada port 80
    networks:
      - mynetwork
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" # phpMyAdmin dipindahkan ke port 8080
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: t3
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
