version: "3.8"

services:
  web:
    build: ./web-app
    container_name: web
    volumes:
      - ./web-app/app:/var/www/html
    ports:
      - "8080:80"
    networks:
      my_network:
        ipv4_address: 172.18.0.10

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: t3
      MYSQL_DATABASE: ecourbancity
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
    networks:
      my_network:
        ipv4_address: 172.18.0.11

networks:
  my_network:
    external: true

volumes:
  db_data:
